### ISSUE TITLE
Problems with Pillow 10.0.0

### ISSUE THREAD

**Issue by webes4** [salabim/salabim#51]
I noticed that the animations no longer work with Pillow==10.0.0. The following error appears:

_AttributeError: 'FreeTypeFont' object has no attribute 'getsize'_

It is necessary to install Pillow==9.5.0 to make it work again.

**Comment by salabim** [comment]
This is a bug in Pillow 10.0.0.
See https://github.com/XingangPan/DragGAN/issues/152

**Comment by salabim** [comment]
Please note that salabim 23.3.5 does support Pillow >= 10.0.0 as well as older versions.
